Updated Bloom Recipe
AllTheMods/Gravitas2 pull request #127
Opened 2024-01-22 03:09 UTC by Nyxane

Made it so the bloom recipes require a minimum temp to work/progress

2024-01-22 12:36 UTC, pietro-lopes commented
is this needed?
`Item.of('tfc:refined_iron_bloom').getId()`
you already have id with the name itself

2024-01-22 15:00 UTC, Nyxane commented
No, it was just an artifact from copying my last function, figured it wouldn't matter :p

2024-01-22 16:18 UTC, pietro-lopes requested changes

2024-01-22 16:18 UTC, pietro-lopes commented on kubejs/server_scripts/recipes/add.js
> +          item: Item.of('tfc:refined_iron_bloom').getId(),
```suggestion
          item: 'tfc:refined_iron_bloom',
```

2024-01-22 16:18 UTC, pietro-lopes commented on kubejs/server_scripts/recipes/add.js
> +          item: Item.of('tfc:raw_iron_bloom').getId(),
```suggestion
          item: 'tfc:raw_iron_bloom',
```

2024-01-25 05:03 UTC, pietro-lopes approved these changes

2024-01-25 17:59 UTC, merged