Drack dev
AllTheMods/Gravitas2 pull request #73
Opened 2023-12-27 11:25 UTC by Drackion

The initial gregified ae2 recipes
most of the base stuff is gregified

2023-12-27 11:35 UTC, screret requested changes

2023-12-27 11:35 UTC, screret commented on kubejs/server_scripts/mods/ae2/gregifyAE2.js
> +                )
could you just do `'gtceu:red_alloy 144'`? it'd be way more compact
or at least put this on 1 line

2023-12-27 11:35 UTC, screret commented on kubejs/server_scripts/mods/ae2/gregifyAE2.js
> +            )
here, just make the 1 thing i/o's a single line, it's more readable that way

2023-12-27 11:36 UTC, screret commented
apply the requested changes to every instance of the thing btw.

2023-12-27 11:52 UTC, Drackion commented
I'll commit those changes tomorrow as i am off my PC fire the night

2023-12-31 00:36 UTC, thevortex commented
i can make the changes if you like @Drackion

2023-12-31 00:52 UTC, Drackion commented
@thevortex sure thx

2023-12-31 01:51 UTC, merged